# Generated by Django 4.2.2 on 2023-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catshop',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
